/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DecksDeckIdStudyRouteImport } from './routes/decks/$deckId/study'
import { Route as DecksDeckIdCardsRouteImport } from './routes/decks/$deckId/cards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdStudyRoute = DecksDeckIdStudyRouteImport.update({
  id: '/decks/$deckId/study',
  path: '/decks/$deckId/study',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdCardsRoute = DecksDeckIdCardsRouteImport.update({
  id: '/decks/$deckId/cards',
  path: '/decks/$deckId/cards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/decks/$deckId/study': typeof DecksDeckIdStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsIndexRoute
  '/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/decks/$deckId/study': typeof DecksDeckIdStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/decks/$deckId/study': typeof DecksDeckIdStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/'
    | '/decks/$deckId/cards'
    | '/decks/$deckId/study'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/decks/$deckId/cards' | '/decks/$deckId/study'
  id:
    | '__root__'
    | '/'
    | '/settings/'
    | '/decks/$deckId/cards'
    | '/decks/$deckId/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  DecksDeckIdCardsRoute: typeof DecksDeckIdCardsRoute
  DecksDeckIdStudyRoute: typeof DecksDeckIdStudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/study': {
      id: '/decks/$deckId/study'
      path: '/decks/$deckId/study'
      fullPath: '/decks/$deckId/study'
      preLoaderRoute: typeof DecksDeckIdStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/cards': {
      id: '/decks/$deckId/cards'
      path: '/decks/$deckId/cards'
      fullPath: '/decks/$deckId/cards'
      preLoaderRoute: typeof DecksDeckIdCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  DecksDeckIdCardsRoute: DecksDeckIdCardsRoute,
  DecksDeckIdStudyRoute: DecksDeckIdStudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
