/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DecksCreateRouteImport } from './routes/decks/create'
import { Route as DecksDeckIdStudyRouteImport } from './routes/decks/$deckId/study'
import { Route as DecksDeckIdGenerateRouteImport } from './routes/decks/$deckId/generate'
import { Route as DecksDeckIdEditRouteImport } from './routes/decks/$deckId/edit'
import { Route as DecksDeckIdCardsRouteImport } from './routes/decks/$deckId/cards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksCreateRoute = DecksCreateRouteImport.update({
  id: '/decks/create',
  path: '/decks/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdStudyRoute = DecksDeckIdStudyRouteImport.update({
  id: '/decks/$deckId/study',
  path: '/decks/$deckId/study',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdGenerateRoute = DecksDeckIdGenerateRouteImport.update({
  id: '/decks/$deckId/generate',
  path: '/decks/$deckId/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdEditRoute = DecksDeckIdEditRouteImport.update({
  id: '/decks/$deckId/edit',
  path: '/decks/$deckId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdCardsRoute = DecksDeckIdCardsRouteImport.update({
  id: '/decks/$deckId/cards',
  path: '/decks/$deckId/cards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks/create': typeof DecksCreateRoute
  '/settings/': typeof SettingsIndexRoute
  '/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/generate': typeof DecksDeckIdGenerateRoute
  '/decks/$deckId/study': typeof DecksDeckIdStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks/create': typeof DecksCreateRoute
  '/settings': typeof SettingsIndexRoute
  '/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/generate': typeof DecksDeckIdGenerateRoute
  '/decks/$deckId/study': typeof DecksDeckIdStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks/create': typeof DecksCreateRoute
  '/settings/': typeof SettingsIndexRoute
  '/decks/$deckId/cards': typeof DecksDeckIdCardsRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/decks/$deckId/generate': typeof DecksDeckIdGenerateRoute
  '/decks/$deckId/study': typeof DecksDeckIdStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decks/create'
    | '/settings/'
    | '/decks/$deckId/cards'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/generate'
    | '/decks/$deckId/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decks/create'
    | '/settings'
    | '/decks/$deckId/cards'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/generate'
    | '/decks/$deckId/study'
  id:
    | '__root__'
    | '/'
    | '/decks/create'
    | '/settings/'
    | '/decks/$deckId/cards'
    | '/decks/$deckId/edit'
    | '/decks/$deckId/generate'
    | '/decks/$deckId/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksCreateRoute: typeof DecksCreateRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  DecksDeckIdCardsRoute: typeof DecksDeckIdCardsRoute
  DecksDeckIdEditRoute: typeof DecksDeckIdEditRoute
  DecksDeckIdGenerateRoute: typeof DecksDeckIdGenerateRoute
  DecksDeckIdStudyRoute: typeof DecksDeckIdStudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/create': {
      id: '/decks/create'
      path: '/decks/create'
      fullPath: '/decks/create'
      preLoaderRoute: typeof DecksCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/study': {
      id: '/decks/$deckId/study'
      path: '/decks/$deckId/study'
      fullPath: '/decks/$deckId/study'
      preLoaderRoute: typeof DecksDeckIdStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/generate': {
      id: '/decks/$deckId/generate'
      path: '/decks/$deckId/generate'
      fullPath: '/decks/$deckId/generate'
      preLoaderRoute: typeof DecksDeckIdGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/edit': {
      id: '/decks/$deckId/edit'
      path: '/decks/$deckId/edit'
      fullPath: '/decks/$deckId/edit'
      preLoaderRoute: typeof DecksDeckIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/cards': {
      id: '/decks/$deckId/cards'
      path: '/decks/$deckId/cards'
      fullPath: '/decks/$deckId/cards'
      preLoaderRoute: typeof DecksDeckIdCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksCreateRoute: DecksCreateRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  DecksDeckIdCardsRoute: DecksDeckIdCardsRoute,
  DecksDeckIdEditRoute: DecksDeckIdEditRoute,
  DecksDeckIdGenerateRoute: DecksDeckIdGenerateRoute,
  DecksDeckIdStudyRoute: DecksDeckIdStudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
