/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeckCategoriesRouteImport } from './routes/deck-categories'
import { Route as IndexRouteImport } from './routes/index'

const DeckCategoriesRoute = DeckCategoriesRouteImport.update({
  id: '/deck-categories',
  path: '/deck-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck-categories': typeof DeckCategoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck-categories': typeof DeckCategoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck-categories': typeof DeckCategoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck-categories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck-categories'
  id: '__root__' | '/' | '/deck-categories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckCategoriesRoute: typeof DeckCategoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/deck-categories': {
      id: '/deck-categories'
      path: '/deck-categories'
      fullPath: '/deck-categories'
      preLoaderRoute: typeof DeckCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckCategoriesRoute: DeckCategoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
